//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Novyjj_proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Остатки.
    /// </summary>
    // *** Start programmer edit section *** (Остатки CustomAttributes)

    // *** End programmer edit section *** (Остатки CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Остатки : ICSSoft.STORMNET.DataObject
    {
        
        private string fДата;
        
        private string fКоличество;
        
        private IIS.Novyjj_proekt.Склад fСклад;
        
        private IIS.Novyjj_proekt.Товар fТовар;
        
        // *** Start programmer edit section *** (Остатки CustomMembers)

        // *** End programmer edit section *** (Остатки CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Остатки.Дата CustomAttributes)

        // *** End programmer edit section *** (Остатки.Дата CustomAttributes)
        [StrLen(255)]
        public virtual string Дата
        {
            get
            {
                // *** Start programmer edit section *** (Остатки.Дата Get start)

                // *** End programmer edit section *** (Остатки.Дата Get start)
                string result = this.fДата;
                // *** Start programmer edit section *** (Остатки.Дата Get end)

                // *** End programmer edit section *** (Остатки.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Остатки.Дата Set start)

                // *** End programmer edit section *** (Остатки.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Остатки.Дата Set end)

                // *** End programmer edit section *** (Остатки.Дата Set end)
            }
        }
        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (Остатки.Количество CustomAttributes)

        // *** End programmer edit section *** (Остатки.Количество CustomAttributes)
        [StrLen(255)]
        public virtual string Количество
        {
            get
            {
                // *** Start programmer edit section *** (Остатки.Количество Get start)

                // *** End programmer edit section *** (Остатки.Количество Get start)
                string result = this.fКоличество;
                // *** Start programmer edit section *** (Остатки.Количество Get end)

                // *** End programmer edit section *** (Остатки.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Остатки.Количество Set start)

                // *** End programmer edit section *** (Остатки.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (Остатки.Количество Set end)

                // *** End programmer edit section *** (Остатки.Количество Set end)
            }
        }
        
        /// <summary>
        /// Остатки.
        /// </summary>
        // *** Start programmer edit section *** (Остатки.Склад CustomAttributes)

        // *** End programmer edit section *** (Остатки.Склад CustomAttributes)
        [PropertyStorage(new string[] {
                "Склад"})]
        [NotNull()]
        public virtual IIS.Novyjj_proekt.Склад Склад
        {
            get
            {
                // *** Start programmer edit section *** (Остатки.Склад Get start)

                // *** End programmer edit section *** (Остатки.Склад Get start)
                IIS.Novyjj_proekt.Склад result = this.fСклад;
                // *** Start programmer edit section *** (Остатки.Склад Get end)

                // *** End programmer edit section *** (Остатки.Склад Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Остатки.Склад Set start)

                // *** End programmer edit section *** (Остатки.Склад Set start)
                this.fСклад = value;
                // *** Start programmer edit section *** (Остатки.Склад Set end)

                // *** End programmer edit section *** (Остатки.Склад Set end)
            }
        }
        
        /// <summary>
        /// Остатки.
        /// </summary>
        // *** Start programmer edit section *** (Остатки.Товар CustomAttributes)

        // *** End programmer edit section *** (Остатки.Товар CustomAttributes)
        [PropertyStorage(new string[] {
                "Товар"})]
        [NotNull()]
        public virtual IIS.Novyjj_proekt.Товар Товар
        {
            get
            {
                // *** Start programmer edit section *** (Остатки.Товар Get start)

                // *** End programmer edit section *** (Остатки.Товар Get start)
                IIS.Novyjj_proekt.Товар result = this.fТовар;
                // *** Start programmer edit section *** (Остатки.Товар Get end)

                // *** End programmer edit section *** (Остатки.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Остатки.Товар Set start)

                // *** End programmer edit section *** (Остатки.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (Остатки.Товар Set end)

                // *** End programmer edit section *** (Остатки.Товар Set end)
            }
        }
    }
}
