//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Novyjj_proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Склад.
    /// </summary>
    // *** Start programmer edit section *** (Склад CustomAttributes)

    // *** End programmer edit section *** (Склад CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Склад : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (Склад CustomMembers)

        // *** End programmer edit section *** (Склад CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Склад.Наименование CustomAttributes)

        // *** End programmer edit section *** (Склад.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Склад.Наименование Get start)

                // *** End programmer edit section *** (Склад.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Склад.Наименование Get end)

                // *** End programmer edit section *** (Склад.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Склад.Наименование Set start)

                // *** End programmer edit section *** (Склад.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Склад.Наименование Set end)

                // *** End programmer edit section *** (Склад.Наименование Set end)
            }
        }
    }
}
